from positional_functions import *
from  serial_comm import*
import time
def process_vertical():
    # home_all()
    # time.sleep(2)
    move_pickup_gantry_to_block_pickup_pos()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_rack()
    time.sleep(2)
    close_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack(155) #########shittttt
    time.sleep(1)
    move_block_tray_forward_by(4)
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_block_tray_backward_by(4)

    move_pickup_gantry_to_block_rotate_pos()
    time.sleep(6)
    block_unclamping()
    time.sleep(2)
    gripper_to_loading_rotating_block()
    time.sleep(2)
    block_clamping()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack()
    rotate_block_Vertical()
    time.sleep(2)
    gripper_to_loading_rotating_block()
    time.sleep(2)
    close_gripper_vertical()
    time.sleep(2)
    block_unclamping()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_pickup_gantry_to_block_holder_pos()
    time.sleep(10)
    open_block_holder()
    time.sleep(2)
    gripper_to_loading_block_holder()
    time.sleep(2)
    close_block_holder()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    gripper_to_loading_block_holder()
    time.sleep(2)
    close_gripper_vertical()
    time.sleep(2)
    open_block_holder()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_pickup_gantry_to_block_pickup_pos()
    time.sleep(14)
    move_block_tray_forward_by(4)
    time.sleep(2)
    gripper_to_loading_rack()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_block_tray_backward_by(4)
    time.sleep(2)



def process_horizontal():
    # home_all()
    # time.sleep(2)
    move_pickup_gantry_to_block_pickup_pos()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_rack()
    time.sleep(2)
    close_gripper_vertical()
    time.sleep(2)
    #shitttt
    gripper_to_loading_above_rack(155)
    time.sleep(1)
    move_block_tray_forward_by(4)
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_block_tray_backward_by(4)

    gripper_to_loading_above_rack()
    time.sleep(2)
    move_pickup_gantry_to_block_rotate_pos()
    time.sleep(10)
    block_unclamping()
    time.sleep(2)
    gripper_to_loading_rotating_block()
    time.sleep(2)
    block_clamping()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    rotate_block_Horizontal()
    time.sleep(2)
    open_gripper_horizontal()
    time.sleep(2)
    gripper_to_loading_rotating_block()
    time.sleep(2)
    close_gripper_horizontal()
    time.sleep(2)
    block_unclamping()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_pickup_gantry_to_block_holder_pos()
    time.sleep(10)
    open_block_holder()
    time.sleep(2)
    gripper_to_loading_block_holder()
    time.sleep(2)
    close_block_holder()
    time.sleep(2)
    open_gripper_horizontal()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    gripper_to_loading_block_holder()
    time.sleep(2)
    close_gripper_horizontal()
    time.sleep(2)
    open_block_holder()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_pickup_gantry_to_block_rotate_pos()
    time.sleep(6)
    block_unclamping()
    time.sleep(2)
    gripper_to_loading_rotating_block()
    time.sleep(2)
    block_clamping()
    time.sleep(2)
    open_gripper_horizontal()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    rotate_block_Vertical()
    time.sleep(2)
    gripper_to_loading_rotating_block()
    time.sleep(2)
    close_gripper_vertical()
    time.sleep(2)
    block_unclamping()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_pickup_gantry_to_block_pickup_pos()
    time.sleep(7)
    ### shit 2
    move_block_tray_forward_by(4)
    time.sleep(2)
    gripper_to_loading_rack()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_block_tray_backward_by(4)
    time.sleep(2)




def pick_block_from_block_tray(num):
    move_tray_to_block_number(num)
    time.sleep(3)
    move_pickup_gantry_to_block_pickup_pos()
    time.sleep(3)


def pick_block_from_block_holder():
    move_pickup_gantry_to_block_holder_pos()
    time.sleep(3)
    open_block_holder()
    time.sleep(3)
    close_block_holder()


def load_block(num):
    open_block_holder()
    pick_block_from_block_tray(num)
    move_pickup_gantry_to_block_holder_pos()
    time.sleep(3)
    close_block_holder()
    time.sleep(3)
    move_pickup_gantry_to_block_pickup_pos()


def remove_block(num):
    pick_block_from_block_holder(num)
    move_pickup_gantry_to_block_pickup_pos()
    time.sleep(3)
    move_tray_to_block_number(num)


def rotate_block():
    move_pickup_gantry_to_block_rotate_pos()
    time.sleep(3)
    move_pickup_gantry_to_block_holder_pos()
    time.sleep(3)
    open_block_holder()
    time.sleep(3)
    close_block_holder()

def next_pickup(n):
    move_tray_to_block_number(n)
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_rack()
    time.sleep(1)
    close_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack(155)
    time.sleep(1)
    move_block_tray_forward_by(4)
    time.sleep(2)
    gripper_to_loading_above_rack()
    time.sleep(2)
    move_block_tray_backward_by(4)

def rest_block():
    move_block_tray_forward_by(4)
    time.sleep(2)
    gripper_to_loading_rack()
    time.sleep(2)
    open_gripper_vertical()
    time.sleep(1)
    open_gripper_vertical()
    time.sleep(2)
    gripper_to_loading_above_rack()

def test():
    next_pickup(1)
    time.sleep(1)
    rest_block()

def home_all():
    reset_all_dynamixels()
    time.sleep(2)
    open_gripper_vertical()
    gripper_to_loading_above_rack()
    open_block_holder()
    time.sleep(2)
    block_unclamping()
    time.sleep(1)
    rotate_block_Vertical()
    time.sleep(1)
    gripper_to_loading_above_rack()
    time.sleep(2)
    home_block_tray_gantry()
    home_block_pickup_gantry()
    home_block_holder()

def present_current():
    dynamixelController.write((UART_1 + DXL_1 + ',' + 'Q' + '?' "\n").encode())
    print(dynamixelController.readline().decode())
#
while(1):
    home_all()
    process_vertical()
    time.sleep(2)
    move_tray_to_block_number(2)
    process_horizontal()
    time.sleep(2)
    move_tray_to_block_number(3)
    process_vertical()
    time.sleep(2)
